### ISSUE TITLE
Brace matching style hidden on selected line

### ISSUE THREAD

**Issue by ismyrnow** [jamiewilson/predawn-syntax#2]
If you are at a character that makes the brace matching style appear (green dotted underline), the underline doesn't show up on the selected line, but does on other lines.

I traced it down to the background color being applied on the line [here](https://github.com/jamiewilson/predawn-syntax/blob/master/stylesheets/base.less#L52). I fixed it in my stylesheet by adding the following style:

``` less
.editor.is-focused .line-number.cursor-line-no-selection, .editor.is-focused .line.cursor-line {
  background-color: transparent !important;
}
```

This removes the darker background color for the selected line, which I don't mind.

If I opened a PR for this, removing the extra selected line styling, would you merge it?
